apiVersion: v1
kind: Service
metadata:
  name: carddeck-webapp-service
  labels:
    app: carddeck-webapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: carddeck-webapp
